### ISSUE TITLE
Incomplete code, please submit a finished work. 

### ISSUE THREAD

**Issue by siyuan126** [i-add/Murder-Mystery_Github#1]
There are several functions missing or uncompleted. Please submit a finished version.

**Comment by i-add** [comment]
Si Yuan

I am unsure why the wrong file was uploaded. Perhaps it is my first time using Github and lack of familiarity.  Here is the completed version that should have been uploaded. Apologies for my confusion.

To clarify, I had completed the project on 6 Oct 2018.  Thanks for your patience.

Stranger
